version: '3'
services:
  grupo35_video_processing_app:
    depends_on:
      postgres:
        condition: service_healthy  
    container_name: grupo35_video_processing_app
    volumes:
      - ./:/app
    build: .
    ports:
      - "8000:8000"