// Code generated by MockGen. DO NOT EDIT.
// Source: process_video_sender.go
//
// Generated by this command:
//
//	mockgen -source=process_video_sender.go -destination=mock/process_video_sender.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	entities "github.com/8soat-grupo35/grupo35-video-processing/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessVideoSender is a mock of ProcessVideoSender interface.
type MockProcessVideoSender struct {
	ctrl     *gomock.Controller
	recorder *MockProcessVideoSenderMockRecorder
	isgomock struct{}
}

// MockProcessVideoSenderMockRecorder is the mock recorder for MockProcessVideoSender.
type MockProcessVideoSenderMockRecorder struct {
	mock *MockProcessVideoSender
}

// NewMockProcessVideoSender creates a new mock instance.
func NewMockProcessVideoSender(ctrl *gomock.Controller) *MockProcessVideoSender {
	mock := &MockProcessVideoSender{ctrl: ctrl}
	mock.recorder = &MockProcessVideoSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessVideoSender) EXPECT() *MockProcessVideoSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockProcessVideoSender) Send(videos entities.VideoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", videos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockProcessVideoSenderMockRecorder) Send(videos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockProcessVideoSender)(nil).Send), videos)
}
