// Code generated by MockGen. DO NOT EDIT.
// Source: transfer_video.go
//
// Generated by this command:
//
//	mockgen -source=transfer_video.go -destination=mock/transfer_video.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransferVideoUseCase is a mock of TransferVideoUseCase interface.
type MockTransferVideoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTransferVideoUseCaseMockRecorder
	isgomock struct{}
}

// MockTransferVideoUseCaseMockRecorder is the mock recorder for MockTransferVideoUseCase.
type MockTransferVideoUseCaseMockRecorder struct {
	mock *MockTransferVideoUseCase
}

// NewMockTransferVideoUseCase creates a new mock instance.
func NewMockTransferVideoUseCase(ctrl *gomock.Controller) *MockTransferVideoUseCase {
	mock := &MockTransferVideoUseCase{ctrl: ctrl}
	mock.recorder = &MockTransferVideoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferVideoUseCase) EXPECT() *MockTransferVideoUseCaseMockRecorder {
	return m.recorder
}

// UploadVideo mocks base method.
func (m *MockTransferVideoUseCase) UploadVideo(key string, videoData []byte, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadVideo", key, videoData, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadVideo indicates an expected call of UploadVideo.
func (mr *MockTransferVideoUseCaseMockRecorder) UploadVideo(key, videoData, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadVideo", reflect.TypeOf((*MockTransferVideoUseCase)(nil).UploadVideo), key, videoData, contentType)
}
