// Code generated by MockGen. DO NOT EDIT.
// Source: status_video_consumer.go
//
// Generated by this command:
//
//	mockgen -source=status_video_consumer.go -destination=mock/video_status_consumer.go
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatusVideoConsumer is a mock of StatusVideoConsumer interface.
type MockStatusVideoConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockStatusVideoConsumerMockRecorder
	isgomock struct{}
}

// MockStatusVideoConsumerMockRecorder is the mock recorder for MockStatusVideoConsumer.
type MockStatusVideoConsumerMockRecorder struct {
	mock *MockStatusVideoConsumer
}

// NewMockStatusVideoConsumer creates a new mock instance.
func NewMockStatusVideoConsumer(ctrl *gomock.Controller) *MockStatusVideoConsumer {
	mock := &MockStatusVideoConsumer{ctrl: ctrl}
	mock.recorder = &MockStatusVideoConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusVideoConsumer) EXPECT() *MockStatusVideoConsumerMockRecorder {
	return m.recorder
}

// ConsumeMessages mocks base method.
func (m *MockStatusVideoConsumer) ConsumeMessages() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConsumeMessages")
}

// ConsumeMessages indicates an expected call of ConsumeMessages.
func (mr *MockStatusVideoConsumerMockRecorder) ConsumeMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMessages", reflect.TypeOf((*MockStatusVideoConsumer)(nil).ConsumeMessages))
}
