// Code generated by MockGen. DO NOT EDIT.
// Source: s3_client.go
//
// Generated by this command:
//
//	mockgen -source=s3_client.go -destination=mock/s3_client.go
//

// Package mock_wrappers is a generated GoMock package.
package mock_wrappers

import (
	context "context"
	reflect "reflect"

	manager "github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockIS3Client is a mock of IS3Client interface.
type MockIS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockIS3ClientMockRecorder
	isgomock struct{}
}

// MockIS3ClientMockRecorder is the mock recorder for MockIS3Client.
type MockIS3ClientMockRecorder struct {
	mock *MockIS3Client
}

// NewMockIS3Client creates a new mock instance.
func NewMockIS3Client(ctrl *gomock.Controller) *MockIS3Client {
	mock := &MockIS3Client{ctrl: ctrl}
	mock.recorder = &MockIS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIS3Client) EXPECT() *MockIS3ClientMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockIS3Client) Upload(ctx context.Context, input *s3.PutObjectInput, opts ...func(*manager.Uploader)) (*manager.UploadOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upload", varargs...)
	ret0, _ := ret[0].(*manager.UploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockIS3ClientMockRecorder) Upload(ctx, input any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockIS3Client)(nil).Upload), varargs...)
}
