// Code generated by MockGen. DO NOT EDIT.
// Source: dynamo.go
//
// Generated by this command:
//
//	mockgen -source=dynamo.go -destination=mock/dynamo.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	entities "github.com/8soat-grupo35/grupo35-video-processing/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockDynamo is a mock of Dynamo interface.
type MockDynamo struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoMockRecorder
	isgomock struct{}
}

// MockDynamoMockRecorder is the mock recorder for MockDynamo.
type MockDynamoMockRecorder struct {
	mock *MockDynamo
}

// NewMockDynamo creates a new mock instance.
func NewMockDynamo(ctrl *gomock.Controller) *MockDynamo {
	mock := &MockDynamo{ctrl: ctrl}
	mock.recorder = &MockDynamoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamo) EXPECT() *MockDynamoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDynamo) Create(video entities.Video) (*entities.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", video)
	ret0, _ := ret[0].(*entities.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDynamoMockRecorder) Create(video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDynamo)(nil).Create), video)
}

// GetByUserId mocks base method.
func (m *MockDynamo) GetByUserId(userId string) ([]entities.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", userId)
	ret0, _ := ret[0].([]entities.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockDynamoMockRecorder) GetByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockDynamo)(nil).GetByUserId), userId)
}

// Update mocks base method.
func (m *MockDynamo) Update(video entities.Video) (*entities.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", video)
	ret0, _ := ret[0].(*entities.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDynamoMockRecorder) Update(video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDynamo)(nil).Update), video)
}
