// Code generated by MockGen. DO NOT EDIT.
// Source: s3.go
//
// Generated by this command:
//
//	mockgen -source=s3.go -destination=mock/s3.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockS3 is a mock of S3 interface.
type MockS3 struct {
	ctrl     *gomock.Controller
	recorder *MockS3MockRecorder
	isgomock struct{}
}

// MockS3MockRecorder is the mock recorder for MockS3.
type MockS3MockRecorder struct {
	mock *MockS3
}

// NewMockS3 creates a new mock instance.
func NewMockS3(ctrl *gomock.Controller) *MockS3 {
	mock := &MockS3{ctrl: ctrl}
	mock.recorder = &MockS3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3) EXPECT() *MockS3MockRecorder {
	return m.recorder
}

// SetBucketName mocks base method.
func (m *MockS3) SetBucketName(bucketName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBucketName", bucketName)
}

// SetBucketName indicates an expected call of SetBucketName.
func (mr *MockS3MockRecorder) SetBucketName(bucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBucketName", reflect.TypeOf((*MockS3)(nil).SetBucketName), bucketName)
}

// UploadFile mocks base method.
func (m *MockS3) UploadFile(key string, fileData []byte, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", key, fileData, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockS3MockRecorder) UploadFile(key, fileData, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockS3)(nil).UploadFile), key, fileData, contentType)
}
