// Code generated by MockGen. DO NOT EDIT.
// Source: sqs.go
//
// Generated by this command:
//
//	mockgen -source=sqs.go -destination=mock/sqs.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	types "github.com/aws/aws-sdk-go-v2/service/sqs/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSQS is a mock of SQS interface.
type MockSQS struct {
	ctrl     *gomock.Controller
	recorder *MockSQSMockRecorder
	isgomock struct{}
}

// MockSQSMockRecorder is the mock recorder for MockSQS.
type MockSQSMockRecorder struct {
	mock *MockSQS
}

// NewMockSQS creates a new mock instance.
func NewMockSQS(ctrl *gomock.Controller) *MockSQS {
	mock := &MockSQS{ctrl: ctrl}
	mock.recorder = &MockSQSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQS) EXPECT() *MockSQSMockRecorder {
	return m.recorder
}

// ConsumeMessages mocks base method.
func (m *MockSQS) ConsumeMessages(consumeFn func(types.Message)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeMessages", consumeFn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeMessages indicates an expected call of ConsumeMessages.
func (mr *MockSQSMockRecorder) ConsumeMessages(consumeFn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMessages", reflect.TypeOf((*MockSQS)(nil).ConsumeMessages), consumeFn)
}

// SendMessage mocks base method.
func (m *MockSQS) SendMessage(message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockSQSMockRecorder) SendMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockSQS)(nil).SendMessage), message)
}
